### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by T0071** [CCareaga/heap_allocator#6]
heap.c:109:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
heap.c:136:53: warning: cast to 'char *' from smaller integer type 'uint'
      (aka 'unsigned int') [-Wint-to-pointer-cast]
    footer_t *wild_foot = (footer_t *) (uintptr_t) ((char *) heap->end ...
                                                    ^
2 warnings generated.

**Comment by Spriithy** [comment]
These are not errors but compiler warnings. These two don't actually interfere with the expected behavior of the heap.

**Comment by CCareaga** [comment]
@Spriithy is correct, nevertheless I have fixed these compiler warnings.
